export const TASK_CENTER_COPY = {
  missingProjectId: "缺少 projectId",
  refresh: "刷新",
  requestIdCopyTitle: "复制失败：请手动复制请求 ID（request_id）",
  runIdCopyTitle: "复制失败：请手动复制 run_id",
  cancelQueuedProjectTaskConfirm: "确认取消该排队中的任务？取消后将不会执行。",
  cancelBatchConfirm: "Cancel this batch task?",

  queueStatusAria: "队列状态 (taskcenter_queue_status)",
  queueInlineWarning: "提示：inline 为进程内单线程 worker，任务会排队串行执行；如需并发请启动 rq+worker。",
  queueHealthCopyButton: "复制 health 请求 ID（request_id）",

  usageLinksPrefix: "常用入口：",
  helpStructuredMemory: "结构化记忆",
  helpWriting: "写作页",
  helpUsageSuffix: "之间来回跳转，查看“提议→应用→回滚”的全链路。",

  changeSetsSectionAria: "变更集 (taskcenter_changesets_section)",
  changeSetsTitle: "变更集（Change Set）",
  changeSetsHint: "按状态筛选；点击条目查看摘要与原始数据（默认折叠）",
  changeSetsStatusHint: "状态说明：未应用=仅提议 | 已应用=已落库 | 已回滚=已撤销 | 失败=执行异常",
  changeSetsEmpty: "暂无变更集",
  changeSetsStatusLabel: "状态",
  changeSetsCounts: {
    all: "总计",
    proposed: "未应用",
    applied: "已应用",
    rolledBack: "已回滚",
    failed: "失败",
  },

  tasksSectionAria: "任务列表 (taskcenter_tasks_section)",
  tasksTitle: "任务（Task）",
  tasksHintPrefix: "失败任务会显示错误摘要与 ",
  tasksStatusHint: "状态说明：排队中→运行中→完成/失败（如失败可用 request_id 查后端日志）",
  tasksEmpty: "暂无任务",
  tasksFailedOnly: "仅看失败",

  projectTasksSectionAria: "项目任务 (taskcenter_projecttasks_section)",
  projectTasksTitle: "项目任务（Project Task）",
  projectTasksHint:
    "用于 worldbook/search/vector/graph 等自动化后台更新；点击条目查看详情（params/result/error 已脱敏）",
  projectTasksStatusHint: "状态说明：排队中→运行中→完成/失败",
  projectTasksLiveStatusPrefix: "Project SSE: ",
  projectTasksEmpty: "暂无项目任务",
  projectTasksFailedOnly: "仅看失败",
  projectTasksRetry: "重试",
  projectTasksCancel: "取消",
  projectTasksIdempotencyPrefix: "幂等键：",

  detailCopyDebug: "复制 Debug 信息",
  detailClose: "关闭",
  detailOverview: "Overview",
  detailActions: "Actions",
  detailGenerationRun: "GenerationRun",
  detailError: "Error",
  detailChangeSet: "ChangeSet",
  detailResults: "Results",
  detailRawJson: "原始数据（JSON）",
  detailNoError: "无错误信息",
  detailMissingChangeSet: "该任务 result 未包含 change_set（可能仍在运行或已失败）。",
  detailApplyRollbackHint: "提示：Apply/Rollback 需要 editor 权限；失败时可复制 request_id 排障。",

  requestIdCopyButton: "复制请求 ID（request_id）",
  projectTaskRunIdCopyButton: "复制 run_id",
  projectTaskRunIdOpenButton: "打开运行记录",
  applyChangeSetButton: "Apply",
  rollbackChangeSetButton: "Rollback",
} as const;
