export const UI_COPY = {
  common: {
    loading: "加载中...",
    droppedParamsPrefix: "参数已自动降级：",
    copy: "复制",
    requestIdLabel: "请求 ID（request_id）",
  },
  brand: {
    appName: "ainovel Atelier",
  },
  nav: {
    home: "首页",
    groupWorkbench: "项目工作台",
    groupView: "查看",
    groupAiConfig: "AI 配置",
    groupAdvancedDebug: "高级调试",
    groupAdmin: "管理",

    wizard: "开工向导",
    projectSettings: "项目设置",
    characters: "角色卡",
    outline: "大纲",
    writing: "写作",
    tasks: "任务中心",
    structuredMemory: "结构化记忆",
    chapterAnalysis: "标注回溯",
    preview: "预览",
    export: "导出",

    worldBook: "世界书",
    rag: "知识库（RAG）",
    graph: "图谱",
    fractal: "分形（Fractal）",
    styles: "风格",
    prompts: "模型配置",
    promptStudio: "提示词工作室",
    adminUsers: "用户管理",

    navMenu: "导航菜单",
    openNav: "打开导航",
    closeNav: "关闭导航",
    chooseProjectHint: "请选择一个项目以进入编辑页。",
    currentProject: "当前项目",
    backToHome: "返回首页",
  },
  structuredMemory: {
    title: "结构化记忆",
    subtitle: "以表格化方式浏览并检索：实体 / 关系 / 事件 / 伏笔 / 证据。",
    bulkOpsHint: "批量操作会生成 Memory Update 的 ops JSON：复制后到 Memory Update 粘贴并 Apply 才会生效。",
    bulkOpsRisk: "风险：Apply 会直接修改记忆表；建议先确认选中范围，必要时先复制 JSON 备份。",
    tabs: {
      entities: "实体",
      relations: "关系",
      events: "事件",
      foreshadows: "伏笔",
      evidence: "证据",
    },
    includeDeleted: "包含已删除（include_deleted）",
    copyDeleteOps: "复制删除操作 JSON",
    copyResolvedOps: "复制标记已解决 JSON",
    deleteOpsLabel: "删除操作（delete ops）",
    resolvedOpsLabel: "标记已解决（resolved ops）",
  },
  auth: {
    loginTitle: "登录",
    loginSubtitle: "使用本地账号登录（cookie session）",
    devFallbackHint: "已启用 DEV 本地模式（dev fallback）：无需登录也可继续体验。",
    devFallbackRiskHint: "风险提示：仅用于开发/演示；生产环境请关闭 dev_fallback（否则可能绕过登录）。",
    devFallbackNextStepHint: "下一步：如需权限/协作，请在下方使用账号登录。",
    continueInDevFallback: "进入首页",
    userIdLabel: "用户 ID",
    userIdPlaceholder: "例如：admin",
    passwordLabel: "密码",
    passwordPlaceholder: "请输入密码",
    reset: "清空",
    login: "登录",
    loggingIn: "登录中...",
    loginSuccess: "登录成功",
    loginFooterHint: "提示：登录态会保存在 cookie 中；退出登录会清理前端本地状态。",
    logout: "退出登录",
    sessionExpireAtPrefix: "会话到期：",
    devFallbackTag: "本地模式（DEV）",
  },
  writing: {
    contextPreview: "上下文预览",
    contextPreviewTitle: "上下文预览",
    contextPreviewSubtitle: "MemoryContextPack / logs",
    contextPreviewRefresh: "刷新",
    contextPreviewClose: "关闭",
    contextPreviewLoadFailedTitle: "加载失败",
    contextPreviewMissingProjectId: "缺少 projectId",
    memoryInjectionToggle: "世界书注入",
    memoryInjectionHint: "启用后，上下文预览会加载 WorldBook 触发结果（Phase 1 占位，暂未接入生成链路）。",
    memoryInjectionDisabledPreview: "世界书注入已关闭。开启后可查看触发条目与 text_md。",
    worldbookSectionTitle: "世界书（WorldBook）",
    contextPreviewRawPack: "raw MemoryContextPack",
    memoryPackEmpty: "当前为空包（Phase 0 占位）。",
  },
  worldbook: {
    entriesCountPrefix: "共 ",
    entriesCountSuffix: " 条",
    refresh: "刷新",
    create: "新建条目",

    bulkMode: "批量模式",
    bulkSelectedPrefix: "已选 ",
    bulkSelectedSuffix: " 条",
    bulkSelectAll: "全选",
    bulkClearSelection: "清空选择",
    bulkEnable: "批量启用",
    bulkDisable: "批量停用",
    bulkPriority: "优先级（priority）",
    bulkCharLimit: "字符上限（char_limit）",
    bulkApply: "应用",
    bulkDelete: "批量删除",
    bulkDuplicateEdit: "复制并编辑",
    bulkNoSelection: "请先选择条目",

    bulkEnableTitle: "批量启用条目？",
    bulkEnableDescPrefix: "将启用 ",
    bulkEnableDescSuffix: " 条。",
    bulkDisableTitle: "批量停用条目？",
    bulkDisableDescPrefix: "将停用 ",
    bulkDisableDescSuffix: " 条。",
    bulkUpdateTitle: "批量更新条目？",
    bulkUpdateDescPrefix: "将更新 ",
    bulkUpdateDescSuffix: " 条。",
    bulkDeleteTitle: "批量删除条目？",
    bulkDeleteDescPrefix: "将删除 ",
    bulkDeleteDescSuffix: " 条，删除后无法恢复。",
    bulkDuplicateTitle: "复制条目？",
    bulkDuplicateDescPrefix: "将复制 ",
    bulkDuplicateDescSuffix: " 条并进入编辑。",

    entriesTitle: "条目列表",
    entriesHint: "关键词条目会按匹配触发；常驻（constant）条目始终注入。点击条目进入编辑。",
    empty: "暂无条目",

    tagEnabled: "启用",
    tagDisabled: "停用",
    tagBlue: "常驻",
    tagGreen: "关键词",
    tagPriorityPrefix: "priority:",
    tagCharLimitPrefix: "limit:",
    keywordsPrefix: "关键词：",
    keywordsNone: "无",

    previewTitle: "预览触发",
    previewHint: "输入一段 query_text，查看会触发哪些条目以及最终拼接的 text_md。",
    previewRun: "预览",
    previewQueryLabel: "query_text",
    previewIncludeConstant: "包含常驻（constant）",
    previewEnableRecursion: "允许递归",
    previewCharLimit: "拼接字符上限",
    previewRequiresSaveHint: "当前条目有未保存修改：预览基于已保存条目，请先保存后再预览。",
    previewUseInDrawerHint: "编辑抽屉打开时请在抽屉内使用预览触发。",
    previewFailed: "预览失败",
    previewTriggeredPrefix: "触发 ",
    previewTriggeredSuffix: " 条",
    previewTruncated: "已截断（超出上限）",
    previewTriggeredList: "触发条目",
    previewNoTriggered: "未触发任何条目",
    previewText: "text_md（最终注入文本）",
    previewTextEmpty: "（空）",

    drawerTitle: "编辑世界书条目",
    newEntryHint: "新条目",
    close: "关闭",
    cancel: "取消",

    formTitle: "标题",
    formEnabled: "启用",
    formConstant: "常驻（constant）",
    formExcludeRecursion: "排除递归",
    formPreventRecursion: "阻止递归",
    formKeywords: "关键词（每行一个）",
    formKeywordsHint: "用于触发匹配（仅非常驻条目生效）。",
    formCharLimit: "字符上限",
    formPriority: "优先级",
    formContent: "内容（Markdown）",

    save: "保存",
    saving: "保存中...",
    saved: "已保存",

    delete: "删除",
    deleted: "已删除",

    discardChangesTitle: "丢弃未保存修改？",
    discardChangesDesc: "关闭前将丢弃当前未保存的修改。",
    discardChangesConfirm: "丢弃",
    discardChangesCancel: "继续编辑",

    validationTitleRequired: "标题不能为空",

    deleteTitle: "删除该条目？",
    deleteDesc: "删除后无法恢复。",
    deleteConfirm: "删除",
    deleteCancel: "取消",

    missingProjectId: "缺少 projectId",
  },
  rag: {
    title: "Vector RAG 管理",
    subtitle: "入库（ingest） / 重建索引（rebuild） / 状态 / 查询（用于排查注入与索引状态）",

    settings: "项目设置（Settings）",
    ingest: "触发入库（Ingest）",
    rebuild: "重建索引（Rebuild）",
    rebuildNeedConfig: "重建索引（Rebuild，需配置）",
    rebuildRecommended: "重建索引（Rebuild，建议）",

    kbTitle: "知识库（KB）",
    kbOrderLabel: "排序（order）",
    kbEnabledLabel: "启用（enabled）",
    kbWeightLabel: "权重（weight）",
    kbNameLabel: "名称（name）",
    kbNewNameLabel: "新建知识库名称（name）",
    kbNewNamePlaceholder: "例如：我的知识库",

    sourcesTitle: "查询来源",
    queryTitle: "查询",
    injectionTitle: "注入结果",
    advancedDebugTitle: "高级调试",
    rerankTitle: "重排（Rerank）",

    ingestResultTitle: "入库结果（Ingest result）",
    rebuildResultTitle: "重建结果（Rebuild result）",
  },
  graph: {
    title: "图谱",
    subtitle: "图谱上下文（GraphContext）：命中实体 + 1-hop 扩散与回放。",

    enabledToggle: "启用（enabled）",
    queryTextLabel: "查询文本（query_text）",
    queryTextPlaceholder: "输入章节文本或关键片段（命中实体名/别名）",
    queryRun: "查询",

    overviewTitle: "结论摘要",
    injectionPreviewTitle: "注入预览（prompt_block.text_md）",
    nodesTitle: "节点",
    matchedLabel: "命中（matched）",
    relationsTitle: "关系",
    evidenceTitle: "证据（source_id 命中节点/边）",
    advancedDebugTitle: "高级调试（raw graph query result）",
  },
  fractal: {
    title: "分形记忆（Fractal）",
    tag: "Fractal",
    subtitle: "用于查看/回放分形记忆注入文本，帮助排查记忆注入与摘要是否按预期工作。",
    usageHint: "何时用：写作中出现“记忆注入不生效/摘要异常/上下文不稳定”等问题时。",
    riskHint: "风险：该页为高级调试，会展示部分 prompt/内部状态；请避免在共享环境泄露项目内容。",
  },
} as const;
