export const UI_COPY = {
  common: {
    loading: "加载中...",
    droppedParamsPrefix: "参数已自动降级：",
  },
  auth: {
    loginTitle: "登录",
    loginSubtitle: "使用本地账号登录（cookie session）",
    devFallbackHint: "当前后端启用了 dev fallback（未登录也可使用本地模式）。",
    continueInDevFallback: "继续进入 Dashboard",
    userIdLabel: "用户 ID",
    userIdPlaceholder: "例如：admin",
    passwordLabel: "密码",
    passwordPlaceholder: "请输入密码",
    reset: "清空",
    login: "登录",
    loggingIn: "登录中...",
    loginSuccess: "登录成功",
    loginFooterHint: "提示：登录态会保存在 cookie 中；退出登录会清理前端本地状态。",
    logout: "退出登录",
    sessionExpireAtPrefix: "会话到期：",
    devFallbackTag: "本地模式",
  },
  writing: {
    contextPreview: "上下文预览",
    contextPreviewTitle: "上下文预览",
    contextPreviewSubtitle: "MemoryContextPack / logs",
    contextPreviewRefresh: "刷新",
    contextPreviewClose: "关闭",
    contextPreviewLoadFailedTitle: "加载失败",
    contextPreviewMissingProjectId: "缺少 projectId",
    memoryInjectionToggle: "世界书注入",
    memoryInjectionHint: "启用后，上下文预览会加载 WorldBook 触发结果（Phase 1 占位，暂未接入生成链路）。",
    memoryInjectionDisabledPreview: "世界书注入已关闭。开启后可查看触发条目与 text_md。",
    worldbookSectionTitle: "世界书（WorldBook）",
    contextPreviewRawPack: "raw MemoryContextPack",
    memoryPackEmpty: "当前为空包（Phase 0 占位）。",
  },
  worldbook: {
    entriesCountPrefix: "共 ",
    entriesCountSuffix: " 条",
    refresh: "刷新",
    create: "新建条目",

    entriesTitle: "条目列表",
    entriesHint: "关键词条目会按匹配触发；常驻（constant）条目始终注入。点击条目进入编辑。",
    empty: "暂无条目",

    tagEnabled: "启用",
    tagDisabled: "停用",
    tagBlue: "常驻",
    tagGreen: "关键词",
    tagPriorityPrefix: "priority:",
    tagCharLimitPrefix: "limit:",
    keywordsPrefix: "关键词：",
    keywordsNone: "无",

    previewTitle: "预览触发",
    previewHint: "输入一段 query_text，查看会触发哪些条目以及最终拼接的 text_md。",
    previewRun: "预览",
    previewQueryLabel: "query_text",
    previewIncludeConstant: "包含常驻（constant）",
    previewEnableRecursion: "允许递归",
    previewCharLimit: "拼接字符上限",
    previewRequiresSaveHint: "当前条目有未保存修改：预览基于已保存条目，请先保存后再预览。",
    previewUseInDrawerHint: "编辑抽屉打开时请在抽屉内使用预览触发。",
    previewFailed: "预览失败",
    previewTriggeredPrefix: "触发 ",
    previewTriggeredSuffix: " 条",
    previewTruncated: "已截断（超出上限）",
    previewTriggeredList: "触发条目",
    previewNoTriggered: "未触发任何条目",
    previewText: "text_md（最终注入文本）",
    previewTextEmpty: "（空）",

    drawerTitle: "编辑世界书条目",
    newEntryHint: "新条目",
    close: "关闭",
    cancel: "取消",

    formTitle: "标题",
    formEnabled: "启用",
    formConstant: "常驻（constant）",
    formExcludeRecursion: "排除递归",
    formPreventRecursion: "阻止递归",
    formKeywords: "关键词（每行一个）",
    formKeywordsHint: "用于触发匹配（仅非常驻条目生效）。",
    formCharLimit: "字符上限",
    formPriority: "优先级",
    formContent: "内容（Markdown）",

    save: "保存",
    saving: "保存中...",
    saved: "已保存",

    delete: "删除",
    deleted: "已删除",

    discardChangesTitle: "丢弃未保存修改？",
    discardChangesDesc: "关闭前将丢弃当前未保存的修改。",
    discardChangesConfirm: "丢弃",
    discardChangesCancel: "继续编辑",

    validationTitleRequired: "标题不能为空",

    deleteTitle: "删除该条目？",
    deleteDesc: "删除后无法恢复。",
    deleteConfirm: "删除",
    deleteCancel: "取消",

    missingProjectId: "缺少 projectId",
  },
} as const;
