export const UI_COPY = {
  common: {
    loading: "加载中...",
    droppedParamsPrefix: "参数已自动降级：",
    copy: "复制",
    requestIdLabel: "请求 ID（request_id）",
  },
  brand: {
    appName: "ainovel Atelier",
  },
  nav: {
    home: "首页",
    wizard: "开工向导",
    projectSettings: "项目设置",
    characters: "角色卡",
    outline: "大纲",
    writing: "写作",
    tasks: "任务中心",
    structuredMemory: "结构化记忆",
    chapterAnalysis: "标注回溯",
    preview: "预览",
    export: "导出",

    worldBook: "世界书",
    graph: "图谱",
    fractal: "分形（Fractal）",
    styles: "风格",
    prompts: "模型配置",
    promptStudio: "提示词工作室",

    navMenu: "导航菜单",
    openNav: "打开导航",
    closeNav: "关闭导航",
    chooseProjectHint: "请选择一个项目以进入编辑页。",
    currentProject: "当前项目",
    backToHome: "返回首页",
  },
  auth: {
    loginTitle: "登录",
    loginSubtitle: "使用本地账号登录（cookie session）",
    devFallbackHint: "当前后端启用了 dev fallback（未登录也可使用本地模式）。",
    continueInDevFallback: "继续进入首页",
    userIdLabel: "用户 ID",
    userIdPlaceholder: "例如：admin",
    passwordLabel: "密码",
    passwordPlaceholder: "请输入密码",
    reset: "清空",
    login: "登录",
    loggingIn: "登录中...",
    loginSuccess: "登录成功",
    loginFooterHint: "提示：登录态会保存在 cookie 中；退出登录会清理前端本地状态。",
    logout: "退出登录",
    sessionExpireAtPrefix: "会话到期：",
    devFallbackTag: "本地模式",
  },
  writing: {
    contextPreview: "上下文预览",
    contextPreviewTitle: "上下文预览",
    contextPreviewSubtitle: "MemoryContextPack / logs",
    contextPreviewRefresh: "刷新",
    contextPreviewClose: "关闭",
    contextPreviewLoadFailedTitle: "加载失败",
    contextPreviewMissingProjectId: "缺少 projectId",
    memoryInjectionToggle: "世界书注入",
    memoryInjectionHint: "启用后，上下文预览会加载 WorldBook 触发结果（Phase 1 占位，暂未接入生成链路）。",
    memoryInjectionDisabledPreview: "世界书注入已关闭。开启后可查看触发条目与 text_md。",
    worldbookSectionTitle: "世界书（WorldBook）",
    contextPreviewRawPack: "raw MemoryContextPack",
    memoryPackEmpty: "当前为空包（Phase 0 占位）。",
  },
  worldbook: {
    entriesCountPrefix: "共 ",
    entriesCountSuffix: " 条",
    refresh: "刷新",
    create: "新建条目",

    bulkMode: "批量模式",
    bulkSelectedPrefix: "已选 ",
    bulkSelectedSuffix: " 条",
    bulkSelectAll: "全选",
    bulkClearSelection: "清空选择",
    bulkEnable: "批量启用",
    bulkDisable: "批量停用",
    bulkPriority: "priority",
    bulkCharLimit: "char_limit",
    bulkApply: "应用",
    bulkDelete: "批量删除",
    bulkDuplicateEdit: "复制并编辑",
    bulkNoSelection: "请先选择条目",

    bulkEnableTitle: "批量启用条目？",
    bulkEnableDescPrefix: "将启用 ",
    bulkEnableDescSuffix: " 条。",
    bulkDisableTitle: "批量停用条目？",
    bulkDisableDescPrefix: "将停用 ",
    bulkDisableDescSuffix: " 条。",
    bulkUpdateTitle: "批量更新条目？",
    bulkUpdateDescPrefix: "将更新 ",
    bulkUpdateDescSuffix: " 条。",
    bulkDeleteTitle: "批量删除条目？",
    bulkDeleteDescPrefix: "将删除 ",
    bulkDeleteDescSuffix: " 条，删除后无法恢复。",
    bulkDuplicateTitle: "复制条目？",
    bulkDuplicateDescPrefix: "将复制 ",
    bulkDuplicateDescSuffix: " 条并进入编辑。",

    entriesTitle: "条目列表",
    entriesHint: "关键词条目会按匹配触发；常驻（constant）条目始终注入。点击条目进入编辑。",
    empty: "暂无条目",

    tagEnabled: "启用",
    tagDisabled: "停用",
    tagBlue: "常驻",
    tagGreen: "关键词",
    tagPriorityPrefix: "priority:",
    tagCharLimitPrefix: "limit:",
    keywordsPrefix: "关键词：",
    keywordsNone: "无",

    previewTitle: "预览触发",
    previewHint: "输入一段 query_text，查看会触发哪些条目以及最终拼接的 text_md。",
    previewRun: "预览",
    previewQueryLabel: "query_text",
    previewIncludeConstant: "包含常驻（constant）",
    previewEnableRecursion: "允许递归",
    previewCharLimit: "拼接字符上限",
    previewRequiresSaveHint: "当前条目有未保存修改：预览基于已保存条目，请先保存后再预览。",
    previewUseInDrawerHint: "编辑抽屉打开时请在抽屉内使用预览触发。",
    previewFailed: "预览失败",
    previewTriggeredPrefix: "触发 ",
    previewTriggeredSuffix: " 条",
    previewTruncated: "已截断（超出上限）",
    previewTriggeredList: "触发条目",
    previewNoTriggered: "未触发任何条目",
    previewText: "text_md（最终注入文本）",
    previewTextEmpty: "（空）",

    drawerTitle: "编辑世界书条目",
    newEntryHint: "新条目",
    close: "关闭",
    cancel: "取消",

    formTitle: "标题",
    formEnabled: "启用",
    formConstant: "常驻（constant）",
    formExcludeRecursion: "排除递归",
    formPreventRecursion: "阻止递归",
    formKeywords: "关键词（每行一个）",
    formKeywordsHint: "用于触发匹配（仅非常驻条目生效）。",
    formCharLimit: "字符上限",
    formPriority: "优先级",
    formContent: "内容（Markdown）",

    save: "保存",
    saving: "保存中...",
    saved: "已保存",

    delete: "删除",
    deleted: "已删除",

    discardChangesTitle: "丢弃未保存修改？",
    discardChangesDesc: "关闭前将丢弃当前未保存的修改。",
    discardChangesConfirm: "丢弃",
    discardChangesCancel: "继续编辑",

    validationTitleRequired: "标题不能为空",

    deleteTitle: "删除该条目？",
    deleteDesc: "删除后无法恢复。",
    deleteConfirm: "删除",
    deleteCancel: "取消",

    missingProjectId: "缺少 projectId",
  },
} as const;
